### ISSUE TITLE
Complete version will come soon

### ISSUE THREAD

**Issue by Galaxy955** [Galaxy955/Gemini_Pro_macOS#1]
**Complete version will come soon!**

I have solved the display problem. The complete version will have independent UI and you can run this script without Typora or other similar apps.

**Comment by Brother-Bob** [comment]
Gemini_Pro_macOS-master % python main.py
Traceback (most recent call last):
  File "/Gemini_Pro_macOS-master/main.py", line 5, in <module>
    from main_window import Main_Window
  File "/Gemini_Pro_macOS-master/main_window.py", line 5, in <module>
    import mistune
ModuleNotFoundError: No module named 'mistune'

**Comment by Galaxy955** [comment]
Complete version has been released.
